CREATE TABLE Ksiazki
(
  `Id` INTEGER AUTO_INCREMENT PRIMARY KEY,
  `WydawnictwoId` INTEGER NOT NULL,
  `Tytuł` VARCHAR(100) NOT NULL,
  `ISBN` VARCHAR(13),
  `Rok wydania` YEAR,
  `Opis` TEXT,
  `Cena` DECIMAL(6,2)
);


CREATE TABLE Autorzy
(
`Id` INTEGER AUTO_INCREMENT PRIMARY KEY,
`Nazwa` VARCHAR(100) NOT NULL
);


CREATE TABLE KsiazkiAutorzy
(
`KsiążkaId` INTEGER NOT NULL,
`AutorId` INTEGER NOT NULL,
PRIMARY KEY(`KsiążkaId`, `AutorId`)
);

CREATE TABLE Wydawnictwa
(
`Id` INTEGER AUTO_INCREMENT PRIMARY KEY,
`Nazwa` VARCHAR(100) NOT NULL,
`Adres` VARCHAR(100)
);
