CREATE TABLE Users
(
Id INTEGER AUTO_INCREMENT PRIMARY KEY,
Nazwa VARCHAR(20) NOT NULL UNIQUE,
Haslo VARCHAR(40) NOT NULL
);

ALTER TABLE Users ADD COLUMN
(
Imie VARCHAR(35) NOT NULL,
Nazwisko VARCHAR(40) NOT NULL,
Email VARCHAR(60) NOT NULL
);
